sc 2142 Create Refunds
justifi-tech/justifi-ruby pull request #6
Opened 2022-02-03 22:02 UTC by jmatheus

Type of Change
--------------

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update
* [ ] This change is in scope for PCI
* [ ] This requires approval from UX
* [ ] This requires approval from Marketing

Links
-----

Steps for Testing/QA
--------------------

2022-02-03 22:05 UTC, pete2786 reviewed
Looks good but fix linter and we need to decide on the description issue here.

2022-02-03 22:19 UTC, jnwaletzko requested changes

2022-02-03 22:19 UTC, jnwaletzko commented on lib/justifi/payment.rb
> +      raise ArgumentError, "Refund reason must be one of the following: #{Justifi::REFUND_REASONS}" unless Justifi::REFUND_REASONS.include? reason
shouldn't we just let the API do this? This makes it another place we have to change it if the api changes.

2022-02-04 16:41 UTC, jnwaletzko approved these changes

2022-02-04 16:41 UTC, jnwaletzko commented on lib/justifi/payment.rb
> +      refund_params = {amount: amount, description: description, reason: reason}
I think `reason` is also optional.

2022-02-04 17:46 UTC, pete2786 approved these changes

2022-02-04 17:47 UTC, merged